version: '3'
services:
  db_postgres_main:
    build: ./db-postgres
    image: otus-hw/db-postgres
    shm_size: 2g
    # volumes:
    #   - "$HOME/otus/volumes/pg_main:/var/lib/postgresql/data:rw"
  db_redis:
    image: redis
  app_sidekiq:
    build: ./app
    image: otus-hw/app_sidekiq
    command: "bundle exec sidekiq -C 'config/sidekiq.yaml' -v -r './initialize.rb'"
    depends_on:
      - db_redis
      - app
  app:
    build: ./app
    image: otus-hw/app
    command: "bundle exec puma -p 3000 -t 1:4 -w 16"
    depends_on:
      - db_postgres_main
    environment:
      RACK_ENV: development
  web:
    build: ./nginx
    image: otus-hw/nginx
    depends_on:
      - app
    ports:
      - 8080:80
  # db_postgres_replica_1:
  #   build: ./db-postgres
  #   image: otus-hw/db-postgres
  #   shm_size: 2g
  #   volumes:
  #     - "$HOME/otus/volumes/pg_replica_1:/var/lib/postgresql/data:rw"
  # db_postgres_replica_2:
  #   build: ./db-postgres
  #   image: otus-hw/db-postgres
  #   shm_size: 2g
  #   volumes:
  #     - "$HOME/otus/volumes/pg_replica_2:/var/lib/postgresql/data:rw"

  citus_master:
    build: ./citus-master
    image: otus-hw/citus-master
    container_name: "citus_master"
    depends_on: [citus_worker_1, citus_worker_2, citus_worker_3, citus_worker_4, citus_worker_5]
    environment: &AUTH
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGUSER: postgres
      PGPASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      CITUS_HOST: citus_master
  citus_worker_1:
    image: "citusdata/citus:12.1.3"
    environment: *AUTH
  citus_worker_2:
    image: "citusdata/citus:12.1.3"
    environment: *AUTH
  citus_worker_3:
    image: "citusdata/citus:12.1.3"
    environment: *AUTH
  citus_worker_4:
    image: "citusdata/citus:12.1.3"
    environment: *AUTH
  citus_worker_5:
    image: "citusdata/citus:12.1.3"
    environment: *AUTH
